In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score

from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression, LinearRegression

In [2]:
df = pd.read_csv("house_train.csv", index_col=0)

In [3]:
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,120,RL,43.0,3182,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,191000
1,20,RL,78.0,10140,Pave,NaN,Reg,Lvl,AllPub,Inside,...,648,Fa,GdPrv,NaN,0,1,2006,WD,Normal,181000
2,50,RL,60.0,9060,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,10,2009,WD,Normal,105000
3,20,RL,NaN,12342,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,GdWo,Shed,600,8,2007,WD,Normal,139900
4,20,RL,75.0,9750,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,Shed,500,4,2007,COD,Normal,157900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,20,RL,78.0,9317,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,3,2007,WD,Normal,176432
1091,50,RL,65.0,7804,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,12,2009,WD,Normal,135000
1092,20,RL,60.0,8172,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,115000
1093,50,RL,55.0,7642,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal,189950
1094,120,RL,53.0,3684,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,174000

In [4]:
numeric = ['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
           'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
           'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch',
           '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']

In [5]:
df2 = df[numeric]
df2

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,120,43.0,3182,7,5,2005,2006,14.0,16,0,...,156,20,0,0,0,0,0,5,2008,191000
1,20,78.0,10140,6,6,1974,1999,99.0,663,377,...,265,0,0,0,0,648,0,1,2006,181000
2,50,60.0,9060,6,5,1939,1950,0.0,204,0,...,0,0,0,0,0,0,0,10,2009,105000
3,20,NaN,12342,5,5,1960,1978,0.0,0,0,...,0,0,36,0,0,0,600,8,2007,139900
4,20,75.0,9750,6,6,1958,1958,243.0,608,0,...,0,0,275,0,0,0,500,4,2007,157900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,20,78.0,9317,6,5,2006,2006,0.0,24,0,...,0,22,0,0,0,0,0,3,2007,176432
1091,50,65.0,7804,4,3,1928,1950,0.0,622,0,...,431,44,0,0,0,0,0,12,2009,135000
1092,20,60.0,8172,5,7,1955,1990,0.0,167,0,...,0,0,0,0,0,0,0,4,2006,115000
1093,50,55.0,7642,7,8,1918,1998,0.0,0,0,...,0,240,0,0,0,0,0,6,2007,189950
1094,120,53.0,3684,7,5,2007,2007,130.0,0,0,...,143,20,0,0,0,0,0,6,2009,174000

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1095 entries, 0 to 1094
Data columns (total 37 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1095 non-null   int64
 1   LotFrontage    895 non-null    float64
 2   LotArea        1095 non-null   int64
 3   OverallQual    1095 non-null   int64
 4   OverallCond    1095 non-null   int64
 5   YearBuilt      1095 non-null   int64
 6   YearRemodAdd   1095 non-null   int64
 7   MasVnrArea     1091 non-null   float64
 8   BsmtFinSF1     1095 non-null   int64
 9   BsmtFinSF2     1095 non-null   int64
 10  BsmtUnfSF      1095 non-null   int64
 11  TotalBsmtSF    1095 non-null   int64
 12  1stFlrSF       1095 non-null   int64
 13  2ndFlrSF       1095 non-null   int64
 14  LowQualFinSF   1095 non-null   int64
 15  GrLivArea      1095 non-null   int64
 16  BsmtFullBath   1095 non-null   int64
 17  BsmtHalfBath   1095 non-null   int64
 18  FullBath       1095 non-null   int64
 19  HalfBath       1095 non-null   int64
 20  BedroomAbvGr   1095 non-null   int64
 21  KitchenAbvGr   1095 non-null   int64
 22  TotRmsAbvGrd   1095 non-null   int64
 23  Fireplaces     1095 non-null   int64
 24  GarageYrBlt    1037 non-null   float64
 25  GarageCars     1095 non-null   int64
 26  GarageArea     1095 non-null   int64
 27  WoodDeckSF     1095 non-null   int64
 28  OpenPorchSF    1095 non-null   int64
 29  EnclosedPorch  1095 non-null   int64
 30  3SsnPorch      1095 non-null   int64
 31  ScreenPorch    1095 non-null   int64
 32  PoolArea       1095 non-null   int64
 33  MiscVal        1095 non-null   int64
 34  MoSold         1095 non-null   int64
 35  YrSold         1095 non-null   int64
 36  SalePrice      1095 non-null   int64
dtypes: float64(3), int64(34)
memory usage: 325.1 KB

In [7]:
df3 = df2.dropna(subset=['LotFrontage'])
df3

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,120,43.0,3182,7,5,2005,2006,14.0,16,0,...,156,20,0,0,0,0,0,5,2008,191000
1,20,78.0,10140,6,6,1974,1999,99.0,663,377,...,265,0,0,0,0,648,0,1,2006,181000
2,50,60.0,9060,6,5,1939,1950,0.0,204,0,...,0,0,0,0,0,0,0,10,2009,105000
4,20,75.0,9750,6,6,1958,1958,243.0,608,0,...,0,0,275,0,0,0,500,4,2007,157900
5,50,70.0,11767,5,6,1946,1995,0.0,352,0,...,0,0,0,0,0,0,0,5,2008,130500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,20,78.0,9317,6,5,2006,2006,0.0,24,0,...,0,22,0,0,0,0,0,3,2007,176432
1091,50,65.0,7804,4,3,1928,1950,0.0,622,0,...,431,44,0,0,0,0,0,12,2009,135000
1092,20,60.0,8172,5,7,1955,1990,0.0,167,0,...,0,0,0,0,0,0,0,4,2006,115000
1093,50,55.0,7642,7,8,1918,1998,0.0,0,0,...,0,240,0,0,0,0,0,6,2007,189950
1094,120,53.0,3684,7,5,2007,2007,130.0,0,0,...,143,20,0,0,0,0,0,6,2009,174000

In [8]:
df4 = df3.dropna(subset=['GarageYrBlt'])

In [9]:
df5 = df4.dropna(subset=['MasVnrArea'])

In [10]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 840 entries, 0 to 1094
Data columns (total 37 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     840 non-null    int64
 1   LotFrontage    840 non-null    float64
 2   LotArea        840 non-null    int64
 3   OverallQual    840 non-null    int64
 4   OverallCond    840 non-null    int64
 5   YearBuilt      840 non-null    int64
 6   YearRemodAdd   840 non-null    int64
 7   MasVnrArea     840 non-null    float64
 8   BsmtFinSF1     840 non-null    int64
 9   BsmtFinSF2     840 non-null    int64
 10  BsmtUnfSF      840 non-null    int64
 11  TotalBsmtSF    840 non-null    int64
 12  1stFlrSF       840 non-null    int64
 13  2ndFlrSF       840 non-null    int64
 14  LowQualFinSF   840 non-null    int64
 15  GrLivArea      840 non-null    int64
 16  BsmtFullBath   840 non-null    int64
 17  BsmtHalfBath   840 non-null    int64
 18  FullBath       840 non-null    int64
 19  HalfBath       840 non-null    int64
 20  BedroomAbvGr   840 non-null    int64
 21  KitchenAbvGr   840 non-null    int64
 22  TotRmsAbvGrd   840 non-null    int64
 23  Fireplaces     840 non-null    int64
 24  GarageYrBlt    840 non-null    float64
 25  GarageCars     840 non-null    int64
 26  GarageArea     840 non-null    int64
 27  WoodDeckSF     840 non-null    int64
 28  OpenPorchSF    840 non-null    int64
 29  EnclosedPorch  840 non-null    int64
 30  3SsnPorch      840 non-null    int64
 31  ScreenPorch    840 non-null    int64
 32  PoolArea       840 non-null    int64
 33  MiscVal        840 non-null    int64
 34  MoSold         840 non-null    int64
 35  YrSold         840 non-null    int64
 36  SalePrice      840 non-null    int64
dtypes: float64(3), int64(34)
memory usage: 249.4 KB

In [11]:
# Разделение на признаки и целевую переменную
X = df5.drop('SalePrice', axis=1).values
y = df5['SalePrice'].values

# Разделение на обучающий и тестовый наборы
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
linmodel = LinearRegression().fit(X_train, y_train)

In [15]:
y_pred = linmodel.predict(X_test)

In [16]:
from sklearn.metrics import mean_squared_error
import numpy as np
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"RMSE: {rmse}")

RMSE: 48514.502154144495

In [17]:
random_forest_model = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest_model.fit(X_train, y_train)

y_pred2 = random_forest_model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred2))
print(f"RMSE: {rmse}")

RMSE: 57969.844587817504

In [20]:
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred3 = knn.predict(X_test)

print("RMSE: ", mean_squared_error(y_test, y_pred3,squared=False))

RMSE:  61091.79762832908

In [21]:
gradboost = GradientBoostingClassifier(random_state=0)
gradboost.fit(X_train, y_train)
y_pred4 = gradboost.predict(X_test)

print("RMSE: ", mean_squared_error(y_test, y_pred4,squared=False))

KeyboardInterrupt:

In [22]:
#Логистическая регрессия
logistic_regression_model = LogisticRegression()
logistic_regression_model.fit(X_train, y_train)

y_pred5 = logistic_regression_model.predict(X_test)
print("RMSE: ", mean_squared_error(y_test, y_pred5,squared=False))

RMSE:  65047.08039365099

/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

# Валидация (Эрдэни)

In [29]:
test = pd.read_csv('house_test.csv',index_col=0)
X_2 = test[['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
           'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
           'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch',
           '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']].fillna(0)

In [30]:
y_pred2 = linmodel.predict(X_2)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:457: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

In [31]:
df_true = pd.read_csv("house_y_true.csv")
y_true = df_true['SalePrice'].values
len(y_true)

365

In [32]:
rmse = np.sqrt(mean_squared_error(y_true, y_pred2))
print(f"RMSE: {rmse}")

RMSE: 40643.44942823689